services:
  db:
    image: postgres:15-alpine
    container_name: minierp_db
    restart: always
    environment:
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_password
      POSTGRES_DB: minierp
    ports:
      - "5432:5432"
    volumes:
      - ./backend/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
